### PR TITLE
Return the raw OSM OAuth2 token in addition to `access_token`

### PR DESCRIPTION
**Pull request by spwoodcock**
> [!WARNING]
> Initially I made this as a backward compatible change.
>
> However I decided to tweak the API slightly to better clarify what things too, making it easier to maintain this into the future.
>
> Users wishing to use the same API can use package version `==1.0.3` without issues and not upgrade.

**Problem**

- The `access_token` supplied from this module can only be deserialised and used by this module to get user data.
- It would be great to have access to the OSM OAuth2 token so the user can call additional OSM endpoints if required.

**Included in this PR - main updates**

- I added some comments to the code in `callback` to describe what is happening.
- Updated the returned dictionary from `callback` to include both `user_data` and `oauth_token`:
  - `user_data` replaces `access_token` we have currently. Although this would better be described as `encoded_user_data`, as it's not an access token nor a JSON of data!
  - `oauth_token` is the OSM OAuth2 access token we can use to call endpoints. Users of this module keeping their code as it is can just ignore this / discard the value if not required. However it is useful to have this value if we want to use it in our backend API.
- The `oauth_token` could be stored in a secure httpOnly cookie from a backend API for persistence, then extracted when we call our backend API for further calls to the OSM API.
- I also renamed `deserialize_access_token` to just `deserialize_data` as we reuse this function for both `user_data` and `oauth_token` now.

**Included in this PR - extras**

- Strips trailing slash from `osm_url` during init, if present.
- Added unit tests for all functionality.
- Added coverage for tests.
- And added a small workflow to run tests on push / PR.

> [!NOTE] 
> Ideally we would call the OSM API from the frontend, however we have no good secure way to store the OSM token outside of a secure httpOnly cookie. OSM will not accept a cookie as auth (they need an `Authorization` header), so this means all OSM API requests need to be mediated by a backend API server we own. The request is sent to our server, the token is extracted from the cookie, then the request is made to OSM and details returned to the frontend.

### CODE REVIEW

**Review by kshitijrajsharma — COMMENTED** [review]
Lets add test cases too , may be something  simple and straightforward ?

**Comment by spwoodcock** [comment]
Tricky to test against the live API, but we could have tests for the serialization 👍

**Comment by spwoodcock** [comment]
Tests added 👍

**Review by kshitijrajsharma — APPROVED** [review]

**Comment by kshitijrajsharma** [comment]
Agree and should go as 2.0.0

**Pull request merged**
